# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'farma' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for farma

  pod 'Firebase/Messaging'

  target 'farmaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
